filebeat.inputs:
- type: log
  paths:
    # Location of all logs inside filebeat container
    - "/var/log/kappa/*.log"
  json.message_key: log
  pipeline: "filebeat"
  
setup.template.enabled: true
setup.template.fields: "fields.yml"
setup.template.overwrite: true

output.elasticsearch: 
  hosts: ["http://localhost:9200"]

setup.kibana:
  host: "locahost:5601"
