# DON'T MODIFY THIS FILE MANUALLY
version: '3.4'
services:
  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.4.0"
    network_mode: "host"
    restart: unless-stopped
    environment:
      - cluster.name=kappa
      - network.host=0.0.0.0
      - discovery.zen.ping.unicast.hosts=node1
      - discovery.zen.minimum_master_nodes=1
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'
    extra_hosts:
      - node1:192.168.1.100
  kibana:
    container_name: kibana
    hostname: kibana
    network_mode: "host"
    restart: unless-stopped
    image: "docker.elastic.co/kibana/kibana:6.4.0"
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    ports:
      - '5601:5601'
  filebeat:
    container_name: filebeat
    hostname: filebeat
    network_mode: "host"
    restart: unless-stopped
    user: root
    image: "docker.elastic.co/beats/filebeat:6.4.0"
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/fields.yml:/usr/share/filebeat/fields.yml
      # Temporarily get news logs
      - /home/kappa/packages/kappa_news/logs/:/var/log/kappa/
      - filebeat:/usr/share/filebeat/data/
    command: filebeat -e -strict.perms=false
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq2
    network_mode: "host"
    restart: unless-stopped
    image: rabbitmq:3-management
    ports:
      - '4369:4369'
      - '5672:5672'
      - '15672:15672'
      - '25672:25672'
      - '35672:35672'
    environment:
      - RABBITMQ_ERLANG_COOKIE=secret
    volumes:
      - ./rabbitmq/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    extra_hosts:
      - "rabbitmq1:192.168.1.100"
      - "rabbitmq2:192.168.1.101"
  flower:
    container_name: flower
    hostname: flower
    network_mode: "host"
    restart: unless-stopped
    image: "mher/flower:latest"
    environment:
      - CELERY_BROKER_URL=amqp://user:bitnami@localhost:5672//
    ports:
      - '5555:5555'
  kafka:
    container_name: kafka
    hostname: kafka
    network_mode: "host"
    restart: unless-stopped
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=192.168.1.100:2181
    volumes:
      - kafka:/bitnami/kafka
    extra_hosts:
      - "kafka:192.168.1.100"
  kafka-manager:
    container_name: kafka-manager
    hostname: kafka-manager
    network_mode: "host"
    restart: unless-stopped
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    environment:
      - ZK_HOSTS=192.168.1.100:2181
      - APPLICATION_SECRET=letmein
    depends_on:
      - kafka
volumes:
  elasticsearch:
    driver: local
  filebeat:
    driver: local
  kafka:
    driver: local
  zookeeper:
    driver: local
  rabbitmq:
    driver: local
