---
version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch:${esver}"
    environment:
      - cluster.name=kappa
      - network.host=0.0.0.0
      - discovery.zen.ping.unicast.hosts=${eshosts}
      - discovery.zen.minimum_master_nodes=1
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports: 
      - '9200:9200'
      - '9300:9300'


  # kibana:
    # container_name: kibana
    # hostname: kibana
    # image: "docker.elastic.co/kibana/kibana:6.4.0"
    # volumes:
      # - ./config/kibana/kibana.yml:/usr/share/kibana/kibana.yml
    # ports: 
      # - '5601:5601'
    # depends_on:
      # - elasticsearch
    # healthcheck:
      # test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/login"]
      # retries: 3


  # zookeeper:
    # container_name: zookeeper
    # hostname: zookeeper
    # image: zookeeper:latest
    # ports:
      # - "2181:2181"
    # environment:
      # ZOO_MY_ID: 1
    # healthcheck:
      # test: ["CMD", "nc", "-z", "localhost", "2181"]
      # interval: 5s
      # retries: 5
# 
# 
  # kafka:
    # container_name: kafka
    # hostname: kafka
    # image: wurstmeister/kafka:latest
    # ports:
      # - "9092:9092"
    # environment:
      # KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      # # HOSTNAME_COMMAND: "hostname -I | awk '{print $1}'"
      # KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # # KAFKA_CREATE_TOPICS: "news:1:3"
    # depends_on:
      # - zookeeper
# 

  # filebeat:
    # container_name: filebeat
    # hostname: filebeat
    # user: root
    # image: "docker.elastic.co/beats/filebeat:6.4.0"
    # volumes:
      # - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      # - ./config/filebeat/fields.yml:/usr/share/filebeat/fields.yml
      # # Temporarily get news logs
      # - /home/kappa/packages/kappa_news/logs/:/var/log/kappa/
      # # Docker log files
      # - /var/lib/docker/containers/:/var/log/containers/
      # - fbdata:/usr/share/filebeat/data/
    # command: filebeat -e -strict.perms=false

  
  # rabbitmq:
    # container_name: rabbitmq
    # hostname: rabbitmq
    # image: "rabbitmq:latest"
    # ports: 
      # - '5672:5672'
      # - '15672:15672'
# 

  # flower:
    # container_name: flower
    # hostname: flower
    # image: "mher/flower:latest"
    # environment:
      # - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    # ports: 
      # - '5555:5555'
# 

volumes:
  esdata:
    driver: local
  fbdata:
    driver: local

