---
version: '3'
services:
  elasticsearch:
    # hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
      - cluster.name=kappa
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - path.data=/usr/share/elasticsearch/data
      - path.logs=/var/log/elasticsearch
      # - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      # - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data
    ports: 
      - '9200:9200'
      - '9300:9300'
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
      retries: 3




      - discovery.zen.ping.unicast.hosts: elasticsearch
      - discovery.zen.minimum_master_nodes: 1
